server:
  port: 8082

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: myapp
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
#      driver-class-name: org.postgresql.Driver
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        connection-test-query: SELECT 1
        connection-timeout: 600000
        idle-timeout: 600000
        max-lifetime: 1800000
        #这边的联接池的我给调小了5倍，它用不了这么大
        maximum-pool-size: 20
        minimum-idle: 5
#上传文件大小
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 500MB
upload:

   imgpath: img/

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
    com.kingweather: DEBUG
#是否启用调度
#schedule: false   #禁用
schedule: true    #启用
